// SGHSS VidaPlus - DER (DBML) - modo seguro
// Gere imagem em: https://dbdiagram.io/
Table Usuario {
  id int [pk, increment]
  nome varchar
  email varchar [unique]
  senhaHash varchar
  perfil varchar
  pacienteId int [null]
  createdAt timestamp
  updatedAt timestamp
}
Table Paciente {
  id int [pk, increment]
  nome varchar
  cpf varchar [unique]
  dataNascimento date
  telefone varchar [null]
  endereco text [null]
  contatoEmergencia varchar [null]
  createdAt timestamp
  updatedAt timestamp
}
Ref: Usuario.pacienteId > Paciente.id